version: "3.3"

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data1/
    environment:
      - POSTGRES_USER=littinrajan
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

volumes:
  postgres_data: